---
title: 'Lab 10: Hierarchical Regression'
date: "Mar 30, 2022"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: TRUE
---

```{r load_package, message = FALSE}
library(psych)
library(car)
library(carData)
```


```{r load data}
data(Tal.Or)
media <- Tal.Or
head(media)
boxplot(media)
hist(media)
```


```{r step1 control}
wrong.lm <- lm(reaction ~ gender + age, media)
summary(wrong.lm)

media.lm1 <- lm(reaction ~ as.factor(gender) + age, media)
summary(media.lm1)
```


```{r step2 pmi}
media.lm2 <- lm(reaction ~ as.factor(gender) + age + pmi, media)
plot(media.lm2) # scale-location plot suggest heteroscedasticity, perhaps because pmi is negatively skewed
# check influence
influenceIndexPlot(media.lm2) # only a few data point with high h values, one point with high cook's distance
media$cook <- cooks.distance(media.lm2)
subset(media, cook > .5) # no cook's distance > .5
# Keep all data
# Show regression output
summary(media.lm2) # notice pmi slope for now
```


```{r step3 importance}
media.lm3 <- lm(reaction ~ as.factor(gender) + age + pmi + import, media)
plot(media.lm3)
influenceIndexPlot(media.lm3) 
summary(media.lm3) # notice change in R-squared and pmi's slope
anova(media.lm1, media.lm2, media.lm3) 

```

