<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 10: Simple Regression</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">R @ PSY Chula</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    RES MTHD/STAT PSY Lab
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="RES_STAT_Lab04.html">Lab 04: Descriptive Statistics</a>
    </li>
    <li>
      <a href="RES_STAT_Lab05.html">Lab 05: Standard Score</a>
    </li>
    <li>
      <a href="RES_STAT_Lab06.html">Lab 06: Visualizing Distribution</a>
    </li>
    <li>
      <a href="RES_STAT_Lab07.html">Lab 07: Sampling Distribution</a>
    </li>
    <li>
      <a href="RES_STAT_Lab08.html">Lab 08: Confidence Interval and t Test</a>
    </li>
    <li>
      <a href="RES_STAT_Lab09.html">Lab 09: Correlation</a>
    </li>
    <li>
      <a href="RES_STAT_Lab10.html">Lab 10: Simple Regression</a>
    </li>
    <li>
      <a href="RES_STAT_Lab12.html">Lab 12: Dependent t Test</a>
    </li>
    <li>
      <a href="RES_STAT_Lab13.html">Lab 13: Independent t Test</a>
    </li>
    <li>
      <a href="RES_STAT_Lab14.html">Lab 14: Chi-Squared Test</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    EXPRM DESIGN/ANA Lab
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="EXPRM_Lab02.html">Lab 02: Randomization</a>
    </li>
    <li>
      <a href="EXPRM_Lab03.html">Lab 03: Power and Sample Size</a>
    </li>
    <li>
      <a href="EXPRM_Lab04.html">Lab 04: One-way ANOVA</a>
    </li>
    <li>
      <a href="EXPRM_Lab05.html">Lab 05: Multiple Comparisons</a>
    </li>
    <li>
      <a href="EXPRM_Lab07.html">Lab 07: Factorial ANOVA</a>
    </li>
    <li>
      <a href="EXPRM_Lab09.html">Lab 09: Data Visualization with ggplot2</a>
    </li>
    <li>
      <a href="EXPRM_Lab10.html">Lab 10: Repeated-Measures ANOVA</a>
    </li>
    <li>
      <a href="EXPRM_Lab11.html">Lab 11: Factorial ANOVA in Repeated-Measures Design</a>
    </li>
    <li>
      <a href="EXPRM_Lab12.html">Lab 12: Means Comparison in Regression</a>
    </li>
    <li>
      <a href="EXPRM_Lab13.html">Lab 13: ANCOVA</a>
    </li>
    <li>
      <a href="EXPRM_Lab14.html">Lab 14: Moderation Analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    SURVEY DESIGN/ANA Lab
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="SURVEY_Lab08.html">Lab 08: Data Cleaning</a>
    </li>
    <li>
      <a href="SURVEY_Lab09.html">Lab 09: Multiple Regression</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lab 10: Simple Regression</h1>
<h4 class="date">Mar 28, 2022</h4>

</div>


<pre class="r"><code># Load packages for this tutorial
library(gridExtra)
library(ggplot2)</code></pre>
<div id="model-fitting" class="section level1">
<h1>Model Fitting</h1>
<p>การวิเคราะห์ข้อมูลทางสถิตินั้นอาจเรียกได้ว่าเป็นการนำแบบจำลองทางคณิตศาสตร์มาใช้อธิบายข้อมูลเชิงประจักษ์ ยกตัวอย่างเช่น เรามีสมมติฐานว่าบุคลิกภาพแบบ A จะสัมพันธ์ทางบวกกับความดันโลหิต หากเราเชื่อว่าอัตราการเปลี่ยนแปลงความดันโลหิตนั้นคงที่เมื่อบุคลิกภาพแบบ A สูงขึ้นหรือลดลง (เช่น ความดันจะเพิ่มขึ้น 5 มม.ปรอท เมื่อคะแนนบุคลิกภาพเพิ่มขึ้น 1 หน่วยเสมอ) เรากำลังจำลองว่าตัวแปรทั้งสองสัมพันธ์กันเชิงเส้นตรง สามารถเขียนเป็นสมการเส้นตรง <span class="math inline">\(y = mx + c\)</span> โดยที่ y คือตัวแปรเกณฑ์ (ความดัน) m คือ ความชัน (ค่าที่บอกความสัมพันธ์ระหวางตัวแปร x และ y เช่น 5 มม.ปรอท ในตัวอย่างนี้) x คือตัวแปรทำนาย (ระดับบุคลิกภาพแบบ A) ส่วน c คือ จุดตัดแกน y ที่บอกว่าเส้นตรงนี้จะตัดแกน y (เมื่อ x = 0) ที่จุดไหน</p>
<p>การวิเคราะห์สถิติจำนวนมากที่นิยมใช้ล้วนตั้งอยู่บนพื้นฐานของสมการเส้นตรง (เช่น t test, correlation, anova, regression) และโปรแกรม R ก็ใช้แนวทางของการสร้างโมเดลเป็นพื้นฐานในการเขียนคำสั่งเช่นกัน</p>
<p>การเขียนโมเดลเส้นตรงให้ตัวแปร x ทำนายตัวแปร y จะอยู่ในรูปสมการ <code>y ~ x</code> โดยที่ y คือ ตัวแปรตาม/ตัวแปรเกณฑ์ ส่วน x คือตัวแปรอิสระ/ตัวแปรทำนาย</p>
<p>คำสั่งในการ fit โมเดลเส้นตรงเข้ากับข้อมูลคือ <code>lm(formula = y ~ x, data)</code> โดย <code>y</code> และ <code>x</code> คือชื่อตัวแปรที่อยู่ใน <code>data</code> คำสั่งนี้จะทำงานโดยการประมาณค่าพารามิเตอร์ (ค่าslope ค่า intercept) คำนวณความคลาดเคลื่อนในการทำนาย ผลการทำนาย ฯลฯ ออกมาเป็น output ที่เราจะเรียกว่า lm object</p>
<p>หลังจากที่เราได้ lm object แล้ว เราจึงค่อยนำมันไปใช้กับคำสั่งอื่นต่อไป เช่น <code>summary()</code> <code>plot()</code> <code>confint()</code> เป็นต้น</p>
<p>ดังนั้นสิ่งที่สำคัญในการวิเคราะห์ข้อมูล คือ การเลือกโมเดลให้เหมาะสมกับข้อมูลที่เราต้องการจะอธิบาย ยกตัวอย่างด้านล่าง เช่น น้ำหนักของรถยนต์ <code>wt</code> สัมพันธ์เชิง<em>เส้นตรง</em>ใน<em>ทางลบ</em>กับอัตราประหยัดน้ำมัน <code>mpg</code> (ยิ่งหนักยิ่งประหยัดน้อย) ในขณะที่ขนาดกระบอกสูบ <code>disp</code> นั้นสัมพันธ์ทางลบแต่เป็นเส้นตรงโค้ง (curvilinear) กับอัตราประหยัดน้ำมั้น <code>mpg</code></p>
<p><img src="RES_STAT_Lab10_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
</div>
<div id="simple-regression" class="section level1">
<h1>Simple Regression</h1>
<p>สำหรับการวิเคราะห์ถดถอยอย่างง่าย (simple regression analysis) เราจะทดสอบความสัมพันธ์เชิงเส้นตรงระหว่างตัวแปรทำนาย (X) และตัวแปรเกณฑ์ (Y)</p>
<p>การ fit โมเดลเส้นตรง ทำโดยใช้คำสั่ง <code>lm(formula, data)</code> โดย <code>formula</code> เป็นโมเดลทางสถิติที่บอกว่าตัวแปรใดเป็นตัวแปรทำนายตัวแปรใดเป็นตัวแปรเกณฑ์ ส่วน <code>data</code> คือ data frame</p>
<p>ในตัวอย่างนี้เราจะใช้ชุดข้อมูล <code>mtcars</code> ซึ่งเป็นข้อมูลเกี่ยวกับรถยนต์รุ่นต่าง ๆ โดยเราต้องการทำนายอัตราการประหยัดน้ำมัน <code>mpg</code> ด้วยตัวแปรน้ำหนักของรถยนต์ <code>wt</code></p>
<pre class="r"><code>data(mtcars)
head(mtcars)</code></pre>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<p>ในโปรแกรม R สมการจะเขียนอยู่ในรูปแบบ <code>y ~ x</code> ดังนั้นสมการ (formula) ของตัวอย่างนี้คือ <code>mpg ~ wt</code> (ใช้นำ้หนักทำนายอัตราประหยัดน้ำมัน)</p>
<p>เมื่อเรา fit โมเดลนี้ด้วยคำสั่ง <code>lm()</code> เราจะบันทึกผลเป็น object ที่ชื่อว่า <code>reg.lm</code> ใน object นี้จะมีข้อมูลที่สำคัญเกี่ยวกับการวิเคราะห์ regression</p>
<p>ในเบื้องต้นเราจะใช้คำสั่ง <code>summary()</code> เพื่อดู output ของการวิเคราะห์ถดถอย และใช้คำสั่ง <code>confint()</code> เพื่อดู 95% CI ของค่าประมาณการพารามิเตอร์ในโมเดล (เช่น ค่า intercept และ slope)</p>
<pre class="r"><code>reg.lm &lt;- lm(mpg ~ wt, mtcars)
summary(reg.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5432 -2.3647 -0.1252  1.4096  6.8727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
## wt           -5.3445     0.5591  -9.559 1.29e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.046 on 30 degrees of freedom
## Multiple R-squared:  0.7528, Adjusted R-squared:  0.7446 
## F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
<pre class="r"><code>confint(reg.lm)</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 33.450500 41.119753
## wt          -6.486308 -4.202635</code></pre>
<p>ส่วน <code>Call:</code> แสดงสูตรโมเดลที่เรากำลังวิเคราะห์<br />
ส่วน <code>Residuals:</code> แสดงความคลาดเคลื่อนในการทำนาย, <span class="math inline">\(Y-\hat{Y}\)</span>.<br />
ส่วน <code>Coefficients:</code> แสดงค่าสัมประสิทธิ์ในสมการเส้นตรง ได้แก่ ค่าจุดตัดแกน Y (intercept) และความชัน (slope) ของตัวแปรทำนาย รวมไปถึงการทดสอบนัยสำคัญทางสถิติของค่าแต่ละตัว<br />
เครื่องหมายดอกจัน (asterisks [*]) เป็นตัวบอกระดับนัยสำคัญทางสถิติที่ระดับ <span class="math inline">\(\alpha\)</span> ต่าง ๆ กัน</p>
<p>ส่วนต่อไปแบ่งได้เป็นดังนี้</p>
<ul>
<li><code>Residual standard error</code> คือ ค่าส่วนเบี่ยงเบนมาตรฐานของความคลาดเคลื่อน (standard deviation of residuals) (errors),</li>
<li>degrees of freedom คือ df ของ residual มีค่าเท่ากับ = <span class="math inline">\(N-k-1\)</span> (k = number of parameters</li>
<li>Multiple R-squared (<span class="math inline">\(R^2\)</span>) คือค่าที่บอกว่าความแปรวนในตัวแปรตาม Y สามารถอธิบายได้ด้วยชุดของตัวแปร X มากน้อยเท่าไหร่</li>
<li>Adjusted <span class="math inline">\(R^2\)</span> คือค่า <span class="math inline">\(R^2\)</span> ที่ปรับแก้จำนวนตัวแปรทำนายแล้วเพื่อให้แม่นยำมากขึ้น (สำหรับ simple regression ที่มีตัวแปรทำนายเพียงตัวเดียว ค่านี้มักใกล้เคียงกับ <span class="math inline">\(R^2\)</span> หรือ un-adjusted <span class="math inline">\(R^2\)</span> )</li>
<li>ค่า <em>F</em> เป็นการทดสอบโมเดลในภาพรวม ใน simple regression ผลการทดสอบค่า F นี้จะสอดคล้องกับการทดสอบค่า slope</li>
<li><em>df</em> เป็นของ regression model (<span class="math inline">\(k\)</span> คือจำนวน) และ <em>df</em> ของ residuals (<span class="math inline">\(N-k-1\)</span>)</li>
<li><em>p</em>-value ของสถิติ <em>F</em></li>
</ul>
<div id="coefficients" class="section level2">
<h2>Coefficients</h2>
<p>ในการวิเคราะห์นี้ เราสามารถนำค่าสัมประสิทธิ์มาเขียนเป็นสมการทำนายได้เป็น <span class="math inline">\(\hat{Y}_{mpg} = 37.285 - 5.344X_{wt}\)</span> โดยค่า intercept และ slope มาจาก output ของ <code>summary()</code></p>
<ul>
<li><p>จุดตัดแกน Y (intercept, <span class="math inline">\(b_0\)</span>) เป็นค่าทำนายตัวแปร Y เมื่อ X = 0 ในตัวอย่างนี้คือ อัตราประหยัดน้ำมันของรถที่มีนำ้หนัก 0 ตัน คือ 37.29 ไมล์ต่อแกลลอน ในกรณี เราสังเกตได้ว่าค่าจุด intercept นั้นไม่ได้ความหมายโดยตัวมันเองเท่าใดนัก เพราะเราไม่ได้ต้องการรู้ว่ารถน้ำหนัก 0 ตันจะมีอัตราประหยัดน้ำมันเท่าใด</p></li>
<li><p>ค่าที่เราสนใจคือ สัมประสิทธิ์ที่แสดงถึงความสัมพันธ์ระหว่าง <code>wt</code> และ <code>mpg</code> นั่นก็คือ ค่าความชันของตัวแปร <code>wt</code>, <em>b</em> = -5.34 ค่าทางลบแสดงว่าเมื่อน้ำหนักรถเปลี่ยนแปลงไปหนึ่งตัน อัตราประหยัดน้ำมันจะเปลี่ยนไปในทิศทางตรงกันข้าม 5.34 ไมล์ต่อแกลลอน</p></li>
</ul>
<pre class="r"><code>reg.lm$coefficients</code></pre>
<pre><code>## (Intercept)          wt 
##   37.285126   -5.344472</code></pre>
</div>
<div id="prediction" class="section level2">
<h2>Prediction</h2>
<p>เราสามารถใช้สมการนี้ทำนายค่า <code>mpg</code> สำหรับค่า <code>wt</code> ที่เราต้องการได้ เช่น หากมีรถที่หนัก 1.5 ตัน เราจะทำนายว่ารถคันนี้มีอัตราประหยัดน้ำมัน <span class="math display">\[ \begin{aligned}
\hat{Y}_{mpg} &amp;= 37.285 - 5.344(1.5) \\
&amp;= 37.285 - 8.016 \\
&amp;= 29.269 
\end{aligned} \]</span></p>
<p>เราสามารถใช้คำสั่ง <code>predict(object, newdata)</code> ได้</p>
<pre class="r"><code>predict(reg.lm, data.frame(wt = 1.5)) # newdata is a data frame with same variable name. </code></pre>
<pre><code>##        1 
## 29.26842</code></pre>
<pre class="r"><code>predict(reg.lm, data.frame(wt = c(1.0, 1.2, 1.4, 1.6))) # predict multiple new values</code></pre>
<pre><code>##        1        2        3        4 
## 31.94065 30.87176 29.80287 28.73397</code></pre>
<pre class="r"><code>predict(reg.lm) # show predicted value for current dataset</code></pre>
<pre><code>##           Mazda RX4       Mazda RX4 Wag          Datsun 710      Hornet 4 Drive   Hornet Sportabout             Valiant 
##           23.282611           21.919770           24.885952           20.102650           18.900144           18.793255 
##          Duster 360           Merc 240D            Merc 230            Merc 280           Merc 280C          Merc 450SE 
##           18.205363           20.236262           20.450041           18.900144           18.900144           15.533127 
##          Merc 450SL         Merc 450SLC  Cadillac Fleetwood Lincoln Continental   Chrysler Imperial            Fiat 128 
##           17.350247           17.083024            9.226650            8.296712            8.718926           25.527289 
##         Honda Civic      Toyota Corolla       Toyota Corona    Dodge Challenger         AMC Javelin          Camaro Z28 
##           28.653805           27.478021           24.111004           18.472586           18.926866           16.762355 
##    Pontiac Firebird           Fiat X1-9       Porsche 914-2        Lotus Europa      Ford Pantera L        Ferrari Dino 
##           16.735633           26.943574           25.847957           29.198941           20.343151           22.480940 
##       Maserati Bora          Volvo 142E 
##           18.205363           22.427495</code></pre>
</div>
<div id="hypothesis-testing" class="section level2">
<h2>Hypothesis testing</h2>
<p>If we takes an <code>Estimate</code> (intercept or slope) and divide by its <code>Std. Error</code>(<em>SE</em>), you will get a <em>t</em>-value. We can then use a <em>t</em>-distribution to calculate a <em>p</em>-value to determine statistical significance. The <em>p</em>-value was a probability of obtaining that <em>t</em> value or more extreme given that a null hypothesis is true. The null hypothesis being tested here was <span class="math inline">\(H_0 : b = 0\)</span>.</p>
<p>A significant test of coefficient (i.e., <em>p</em> &lt; .05) suggests that, if the relationship does not exist, it is very unlikely to obtain this magnitude of slope. Thus, we <em>infer</em> that the relationship <em>may</em> exist (accepting <span class="math inline">\(H_a\)</span>). In other words, the coefficient <em>may not be zero</em>.</p>
</div>
<div id="confidence-interval-of-coefficients" class="section level2">
<h2>Confidence interval of coefficients</h2>
<p>We can calculate a 95% CI for each coefficient.</p>
<pre class="r"><code>confint(reg.lm) #default setting is 95% CI</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 33.450500 41.119753
## wt          -6.486308 -4.202635</code></pre>
<pre class="r"><code>confint(reg.lm, level = .99) # set to 99% CI</code></pre>
<pre><code>##                 0.5 %    99.5 %
## (Intercept) 32.121659 42.448593
## wt          -6.881997 -3.806946</code></pre>
<p>The 99% CI is <em>wider</em> than the 95% CI because the 99% CI represents a higher chance of being correct about the population value. Thus, it includes a larger margin of error.</p>
<p>Even with the 99% confidence level, the CI of <code>wt</code> slope does not contain zero. This gives us confidence that the negative relationship between <code>wt</code> and <code>mpg</code> may really exists.</p>
</div>
<div id="standardized-coefficients-or-betas" class="section level2">
<h2>Standardized coefficients or betas</h2>
<p>Raw coefficients are in a unit of variable <em>Y</em>, which make it hard to judge the strengh of relationship. To solve this problem, we could standardize the coefficient to make it easier to interpret. This standardized regression coefficients are also called <em>beta</em> (<span class="math inline">\(\beta\)</span>) by some statistical programs.</p>
<pre class="r"><code># install.packages(&quot;QuantPsyc&quot;)
library(QuantPsyc)
lm.beta(reg.lm)</code></pre>
<pre><code>##         wt 
## -0.8676594</code></pre>
<p>The standardized coeff. of -.87 was quite a strong negative relationship.</p>
</div>
</div>
<div id="scatter-plot" class="section level1">
<h1>Scatter Plot</h1>
<p>To create a scatter plot with a fit line.</p>
<ol style="list-style-type: decimal">
<li>Use <code>ggplot(data, aes(x, y))</code> to specify the data and aesthetic mapping,</li>
<li>Use <code>geom_point()</code> to make a scatter plot,</li>
<li>Use <code>geom_smooth(method = , se = )</code> to add the best fit line. The <code>method</code> option refers to a method to create a smooth line, which would be <code>lm</code> for a linear model. The option <code>se</code> is for confidence interval around the predicted line, which is <code>TRUE</code> by default.</li>
</ol>
<pre class="r"><code>ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() + # scatter dots
  geom_smooth(method = lm, se = TRUE) + #add a linear fit line to the previous plot
  theme_classic()</code></pre>
<p><img src="RES_STAT_Lab10_files/figure-html/scatterplot-1.png" width="672" /></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
